Add deploy-verification-environment
shisama/blog-private pull request #1
Opened 2023-01-30 17:05 UTC by shisama

2023-01-31 05:07 UTC, shisama commented on articles/2023/deploy-verification-environment/README.md
> +各エンジニアのプルリクエストがマージされるとレビュー用の環境にアプリケーションが検証用の開発環境へデプロイされるようになっています。
```suggestion
各エンジニアのプルリクエストがマージされるとアプリケーションが検証用の開発環境へデプロイされるようになっています。
```

2023-01-31 05:09 UTC, shisama commented on articles/2023/deploy-verification-environment/README.md
> +
「認証によるアクセス制限」はNext.jsのミドルウェアを利用して認証機能を実装しています。

みたいな一文を追記する。

2023-01-31 05:10 UTC, shisama commented on articles/2023/deploy-verification-environment/README.md
> +3-2. Next.jsをビルドし、Dockerイメージを生成
```suggestion
3-1. APIのモックサーバーをCloud Runへデプロイ（図内では省略）。  
3-2. Next.jsをビルドし、Dockerイメージを生成  
```

2023-01-31 05:12 UTC, shisama commented on articles/2023/deploy-verification-environment/README.md
> +3-2. Next.jsをビルドし、Dockerイメージを生成
```suggestion
3-1. 専用のAPIサーバーをCloud Runへデプロイ（図内では省略）。
3-2. Next.jsをビルドし、Dockerイメージを生成
```

2023-01-31 05:12 UTC, shisama commented on articles/2023/deploy-verification-environment/README.md
> +## APIのモックサーバーをCloud Runへデプロイ
```suggestion
## 専用のAPIサーバーをCloud Runへデプロイ
```

2023-01-31 05:14 UTC, shisama commented on articles/2023/deploy-verification-environment/README.md
> +3-2. Next.jsをビルドし、Dockerイメージを生成
APIサーバについては全体的に削除してもよさそう

2023-01-31 05:41 UTC, shisama commented on articles/2023/deploy-verification-environment/README.md
> +
タグ付けの話をする。

イメージにタグをつけているのは、Cloud Runへデプロイするときにタグでイメージを指定するからタグ付けをしている。
同じプルリクエストで何回もデプロイをするときに、回数はどうでもよくて最新のさえとれればいいので、最新のイメージにタグをつける。そうすればすでに上がっている一つ前のイメージからはタグが削除されて最新のイメージだけにそのタグがついている状態。

2023-01-31 05:43 UTC, shisama commented on articles/2023/deploy-verification-environment/README.md
> +`for d in $(gcloud container images list-tags ${{ env.IMAGE }} --filter='-tags:*' --format="get(digest)"); do`はタグ付けされていないイメージの削除を行っています。
同じプルリクエストで複数回デプロイされたときに残っているタグつけされていない古いイメージを削除するため。

2023-01-31 05:47 UTC, shisama commented on articles/2023/deploy-verification-environment/README.md
> +![](./applying-deploy-label.png)
画像内のURLに対して、a.run.appだけ残して残りのURL文字列すべてにモザイクかける

2023-01-31 05:59 UTC, shisama commented on articles/2023/deploy-verification-environment/README.md
> +  run: docker build --cache-from ${{ env.IMAGE }},${{ env.CACHE_IMAGE }} -t ${{ env.IMAGE }} -f ./Dockerfile .
マルチステージビルドしているため、2つのイメージをひっぱてきている。
env.IMAGEのほうはNext.jsのビルド結果が入っていて、こちらのDockerのイメージは毎回ビルドしている。ただし、Next.jsのビルドはGitHub Actionsで行っているため、Next.jsのビルドのキャッシュはそちらに保持されていて、ビルド時に利用している。

env.CACHE_IMAGEのほうはnpm ci した結果のnode_modulesが入っているDockerイメージを作っている。こちらはビルド時にはタグ付けされない。なぜならpackage-lockは頻繁に書き換えられないと想定して、リビジョン管理する必要がなく、常に最新のものをひっぱってくればOKなため。ただし、プルリクエストによってはpackage-lockが変わる場合もあるが、それはDocker側でファイルの変更を検知して`npm ci`しなおしてDockerイメージをビルドしなおすため、プルリクエスト内のpackage-lockの変更も反映される。

2023-01-31 06:05 UTC, shisama commented on articles/2023/deploy-verification-environment/README.md
> +
```
- name: Tag a container image
  run: docker tag $(docker images --filter 'label=build-stage=installer' -q | head -n 1) ${{ env.CACHE_IMAGE }}
```

npm ciした結果がビルドされたイメージに対して`cache`というタグを付けます。`CACHE_IMAGE`には`イメージ名:タグ名`を指していて、`asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend-pr-verification-environment:cache`という文字列が格納されています。（`asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend-pr-verification-environment`がイメージ名、`cache`がタグ）

2023-01-31 06:09 UTC, shisama commented on articles/2023/deploy-verification-environment/README.md
> +
`$(docker images --filter 'label=build-stage=installer' -q | head -n 1)`はGitHub Actionsの環境内にあるDockerイメージの一覧から`label=build-stage=installer`でフィルタされたイメージのハッシュ値の一覧の1行目を取ってきて、それに対して`cache`というタグを付けている。

2023-01-31 06:10 UTC, shisama commented on articles/2023/deploy-verification-environment/README.md
> +
読者がイメージしやすいように、ここにDockerfileの中身(./Dockerfile)を書いてしまう。SKIP_PREPARE環境変数の箇所だけ削除する。

2023-01-31 06:17 UTC, shisama commented on articles/2023/deploy-verification-environment/README.md
> +
Next.jsを含む現在のバンドラーの仕組みだとDocker内でビルドせずにGitHub Actions側（ホスト側）でビルドした結果をDockerコンテナイメージに取り込むことが大切です。
なぜなら、Dockerコンテナ内にビルドのキャッシュを含めてビルドしないと差分キャッシュが効かないため、パフォーマンスが悪くなります。ただ、ビルドキャッシュをコンテナにコピーするのは必要ないものを取り込むことになるのでホスト側にキャッシュは保持しておきます。

2023-02-02 09:28 UTC, shisama commented on articles/2023/deploy-verification-environment/README.md
> +## APIのモックサーバーをCloud Runへデプロイ
全体的にAPIサーバーについては削除する

2023-02-14 06:08 UTC, shisama commented on articles/2023/deploy-verification-environment/README.md
> +3-2. Next.jsをビルドし、Dockerイメージを生成
https://github.com/shisama/blog-private/pull/1/commits/25a5bd370c450fbcfa67f93d28c1b4fa1ad33e3b

2023-02-14 12:16 UTC, shisama commented on articles/2023/deploy-verification-environment/README.md
> +
まとめに書いた

2023-03-19 13:54 UTC, NamedPython commented on articles/2023/deploy-verification-environment/README.md
> +```yaml
[実際の中身](https://github.com/shisama/deploy-Nextjs-to-CloudRun-PR/blob/main/.github/workflows/deploy.yaml)と少し変えていたりしますか？
`${{ github.workspace }}/.next/cache` の記述がなかったりするので、ビルドキャッシュを使う文面と整合性がとれないです。

2023-03-19 14:04 UTC, NamedPython commented on articles/2023/deploy-verification-environment/README.md
> +### Next.js のビルドと Docker イメージの作成
- Next.js のビルド
- Docker イメージのビルド

で内容が分けられそうなので、章を分けるのはいかがでしょうか？
加えて、後述されている「なぜホスト側で `npm run build` するのか」の文章をここに持ってくることで、後から書くよりも疑問を早々に解消できます。意図と違ったらごめんなさい。

余計なことに気づいたんですが、ビルドキャッシュのパスが `.next/cache` で、これをイメージにコピーするのは避けたい、という意図だと思うんですが、`Dockerfile` を参照すると `COPY --chown=nextjs:nodejs ./.next ./.next` のようにすべて `COPY` してしまっているため、結果的にすべて取り込んでしまっています。
なので、意図側を修正する必要があるかもしれません。一旦以下には2つの意図がある旨のサンプルを書いておきますが、片方を消すことになると思います。

> Next.jsはビルド時にキャッシュ `.next/cache` を利用して差分ビルドできるのですが、Dockerビルド内でやろうとするとワークスペース内に余計なファイルをコピーすることになる上、

```
### Next.js のビルド

Next.jsを含む現在のバンドラーの仕組みを考慮すると、GitHub Actions側(ホスト側)でビルドした結果をDockerビルド時に取り込む方が効率的にビルドできます。

Next.jsはビルド時にキャッシュ `.next/cache` を利用して差分ビルドできるのですが、Dockerビルド内でやろうとするとワークスペース内に余計なファイルをコピーすることになる上、ビルド時に生成されたキャッシュを成果物として取り出すのが手間です。

そのため、ホスト側で前回のビルドキャッシュを持ち、ホスト側でビルドをした上で成果物を `COPY` することで最大効率のビルドができます。

...

### Docker のビルド

次に、Next.jsのビルド結果含むDockerイメージをビルドしています。このイメージがCloudRunにデプロイされます。

```yaml
- name: Build a docker image
  run: docker build --cache-from ${{ env.IMAGE }},${{ env.CACHE_IMAGE }} -t ${{ env.IMAGE }} -f ./Dockerfile .
```
...
```

2023-03-19 14:09 UTC, NamedPython commented on articles/2023/deploy-verification-environment/README.md
> +まず`-f ./Dockerfile`についてですが、Dockerfileは次のようにマルチステージビルドを利用しています。
```suggestion
まずは `-f` で指定されている `Dockerfile` を見ていきます。

キャッシュをヒットさせやすくするためにマルチステージビルドを利用しているため、`Dockerfile` の中身に続いて仕組みを解説していきます。
```

2023-03-19 14:48 UTC, NamedPython commented on articles/2023/deploy-verification-environment/README.md
> +次に、Next.jsのにビルド結果のファイルをデプロイするためのDockerイメージをビルドしています。
以下について構造化の提案をします。かなり説明の順番を前後させています。
意図としては、Actionsの話とDockerfileの話について行き来が発生していたため、できる限りまとめることで認知負荷を下げる意図です。

[こちらのコメント](https://github.com/shisama/blog-private/pull/1/files#r1141371495` で提案した通り、「Docker イメージのビルド」という章分けをした前提の構造化になります。ネストをふたつ下げるので、好みに合わなければ大丈夫です。

---
### Docker イメージのビルドとプッシュ

次に、Next.jsのにビルド結果のファイルをデプロイするためのDockerイメージをビルドしていきます。

GitHub Actionsでは以下のように定義しています。

```yaml
- name: Build a docker image
  run: docker build --cache-from ${{ env.IMAGE }},${{ env.CACHE_IMAGE }} -t ${{ env.IMAGE }} -f ./Dockerfile .
- name: Tag a container image
  run: docker tag $(docker images --filter 'label=build-stage=installer' -q | head -n 1) ${{ env.CACHE_IMAGE }}
- name: Push the docker image
  run: |
    docker push ${{ env.IMAGE }} &
    docker push ${{ env.CACHE_IMAGE }} &
    wait
```

ビルド時に利用するイメージキャッシュ( `installer` ステージ)も併せてプッシュしています。

このイメージはすべてのプルリクエストで `cache` というタグの同じイメージを共有しています。
プロトタイプの段階では、このイメージが頻繁に変わることないと見込んで、同じタグ名を使っています。
現在はまだプロトタイプということもあり、Renovateなどで自動でアップデートする設定なども入れておらず、手動で行っています。

ただ、プロトタイプより後のフェーズになると、セキュリティパッチは可能な限り素早く取り込みたいので、ライブラリのアップデート頻度も変わる可能性があります。
そうなると、このキャッシュの方法も変える必要があるかもしれません。

#### ビルド時の引数について

- `-t ${{ env.IMAGE }}`
  - ビルドしたイメージにタグ付けをします
  - `asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend-pr-verification-environment:${{ github.head_ref }}` で構成される文字列です
  - `${{ github.head_ref }}` はプルリクエストのブランチ名に置き換わります
  - `${{ secrets.GCP_PROJECT_ID }}` はGCPのプロジェクトIDに置き換わります
- `--cache-from ${{ env.IMAGE }},${{ env.CACHE_IMAGE }}`
  - 前回のビルドイメージおよびnpmキャッシュイメージをビルド時に利用する、という指定です

#### Dockerfile

キャッシュをヒットさせやすくするためにマルチステージビルドを利用しているため、`Dockerfile` の中身に続いて仕組みを解説していきます。

```Dockerfile
# Build the source code
FROM node:16-alpine AS installer
LABEL build-stage=installer
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
ENV SKIP_PREPARE 'true'
RUN npm ci --production
# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
ENV NEXT_TELEMETRY_DISABLED 1
# Production image, copy all the files and run next
FROM node:16-alpine AS runner
WORKDIR /app
ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
COPY --from=installer --chown=nextjs:nodejs /app/node_modules ./node_modules
COPY --from=installer --chown=nextjs:nodejs /app/package.json ./package.json
# Copy files from the host to perform next build caching on the host
COPY --chown=nextjs:nodejs ./.next ./.next
COPY --chown=nextjs:nodejs ./next.config.js ./
USER nextjs
EXPOSE 3000
ENV PORT 3000
ENV NO_NEXT_TRANSPILE 'true'
CMD ["npm", "start"]
```

##### `installer` ステージ

`installer` はnpmパッケージをインストールし、`node_modules` に配置するためのステージです。この後のいくつかのステージで利用します。

##### `runner` ステージ

`runner` は名前の通りNext.jsの実行を含むステージです。 すでにインストールされたnpmパッケージを `installer` ステージからコピーして利用します。

```Dockerfile
COPY --from=installer --chown=nextjs:nodejs /app/node_modules ./node_modules
COPY --from=installer --chown=nextjs:nodejs /app/package.json ./package.json
```

同様に、Next.jsのビルド結果やNext.jsの設定をホスト側からコピーします。

```Dockerfile
COPY --chown=nextjs:nodejs ./.next ./.next
COPY --chown=nextjs:nodejs ./next.config.js ./
```

2023-03-19 15:07 UTC, NamedPython commented on articles/2023/deploy-verification-environment/README.md
> +この仕組みは業務委託でお手伝いいただいている[@chimame_rt](https://twitter.com/chimame_rt)さんが考案し設計してくれました 👏
悲しいですが、より正確に書くのであれば...

```suggestion
この仕組みは業務委託でお手伝いいただいていた[@chimame_rt](https://twitter.com/chimame_rt)さんが考案し設計してくれました 👏
```

2023-03-19 15:08 UTC, NamedPython commented on articles/2023/deploy-verification-environment/README.md
> +Next.jsを含む現在のバンドラーの仕組みだとコンテナ内でビルドせずにGitHub Actions側（ホスト側）でビルドした結果をコンテナに取り込むことが大切です。
[こちらのコメント](https://github.com/shisama/blog-private/pull/1/files#r1141371495) の通り、上の方に移す提案をしています。

2023-03-20 00:34 UTC, shisama commented on articles/2023/deploy-verification-environment/README.md
> +```yaml
ありがとうございます！ちなみにこの記事すでに長いので、キャッシュに関して全面的に削除するか別の記事に逃がすのもありかなと考えています。この記事は単純にデプロイする仕組みにフォーカスしてもいいかなと。

2023-04-26 08:30 UTC, shisama commented on articles/2023/deploy-verification-environment/README.md
> +### Next.js のビルドと Docker イメージの作成
認証も必要なので、以下のような構成に変更しました。

```
Step 1. エンジニアがプルリクエストを作成（上図の1）  
Step 2. プルリクエストにラベルを適用してGitHub Actionsを起動（上図の2）  
Step 3. Next.jsのビルド  
Step 4. Google Cloud の認証
Step 5. Dockerイメージのビルドとプッシュ（上図の3、4）  
Step 6. Next.jsのアプリケーションをCloud Runへデプロイ（上図の5）  
Step 7. デプロイに成功したサービスのURLをプルリクエストにコメントする  
```

2023-04-26 08:36 UTC, shisama commented on articles/2023/deploy-verification-environment/README.md
> +次に、Next.jsのにビルド結果のファイルをデプロイするためのDockerイメージをビルドしています。
このまままるっといただきます 🙏

2023-04-26 10:56 UTC, shisama commented on articles/2023/deploy-verification-environment/README.md
> +```yaml
Nextのキャッシュについてはリンク先を参照で逃げています。

> CI上でのNext.jsのビルドのキャッシュについてはこちらのページをご参照ください。
> https://nex.js .org/docs/advanced-features/ci-build-caching#GitHub-actions

2023-05-11 23:57 UTC, NamedPython requested changes

2023-05-11 23:57 UTC, NamedPython commented on articles/2023/deploy-verification-environment/README.md
> +google-GitHub-actions/authというGitHub Actionsを利用しています。
ちょっと細かいですが 🙏 

```suggestion
google-github-actions/authというGitHub Actionsを利用しています。
```

2023-05-11 23:57 UTC, NamedPython commented on articles/2023/deploy-verification-environment/README.md
> +[https://nex.js .org/docs/advanced-features/ci-build-caching#GitHub-actions:embed:cite]
typoだったりリンクの変化があったりしたので、該当部分のURLを再度提案してます

```suggestion
[https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#github-actions:embed:cite]
```

2023-05-11 23:57 UTC, NamedPython commented on articles/2023/deploy-verification-environment/README.md
> +Next.jsをビルドしますが、ここでGitHub Actionsの実行効率を上げるために`node_modules`はあらかじめキャッシュされているものを使います。
```suggestion
Next.jsをビルドしますが、実行効率を上げるために`node_modules`はあらかじめキャッシュされているものを使います。
```

2023-05-11 23:57 UTC, NamedPython commented on articles/2023/deploy-verification-environment/README.md
> +Next.jsをビルドしますが、ここでGitHub Actionsの実行効率を上げるために`node_modules`はあらかじめキャッシュされているものを使います。
```suggestion
Next.jsをビルドしますが、実行効率を上げるために`node_modules`はあらかじめキャッシュされているものを使います。
```

2023-05-11 23:57 UTC, NamedPython commented on articles/2023/deploy-verification-environment/README.md
> +各エンジニアのプルリクエストがマージされるとアプリケーションが検証用の開発環境へデプロイされるようになっています。
```suggestion
各エンジニアのプルリクエストがマージされるとアプリケーションが検証用の環境へデプロイされるようになっています。
```

2023-05-11 23:57 UTC, NamedPython commented on articles/2023/deploy-verification-environment/README.md
> +`for d in $(gcloud container images list-tags ${{ env.IMAGE }} --filter='-tags:*' --format="get(digest)"); do`はタグ付けされていないイメージの削除を行っています。
```suggestion
`for d in ... do`のブロックで、タグ付けされていないイメージの削除を行っています。
```

2023-05-30 07:14 UTC, shisama commented on articles/2023/deploy-verification-environment/README.md
> +[https://nex.js .org/docs/advanced-features/ci-build-caching#GitHub-actions:embed:cite]
Prettierがたまにぶっ壊してくるんですよね。jsのまえには`.`を付けなさいって。

2023-05-31 00:33 UTC, NamedPython commented on articles/2023/deploy-verification-environment/README.md
> +[https://nex.js .org/docs/advanced-features/ci-build-caching#GitHub-actions:embed:cite]
だいぶ破壊神Prettierですね...
修正ありがとうございます。

2023-05-31 00:34 UTC, NamedPython approved these changes
LGTM! お疲れ様でした!

2023-06-10 23:52 UTC, merged